package main

// DO NOT EDIT, this file is generated by hover at compile-time for the hwebview plugin.

import (
	"path"

	hwebview "github.com/Winwisly100/hwebview/go"
	"github.com/asticode/go-astikit"
	"github.com/asticode/go-astilectron"
	flutter "github.com/go-flutter-desktop/go-flutter"
	"github.com/mitchellh/go-homedir"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	home, _ := homedir.Dir()
	options = append(options, flutter.AddPlugin(&hwebview.HwebviewPlugin{
		Options: astilectron.Options{
			AppName:           "ION",
			BaseDirectoryPath: path.Join(home, "maintemplate"),
		},
		WindowsOptions: &astilectron.WindowOptions{
			Center: astikit.BoolPtr(true),
			Height: astikit.IntPtr(700),
			Width:  astikit.IntPtr(400),
			WebPreferences: &astilectron.WebPreferences{
				Webaudio: astikit.BoolPtr(true),
				Webgl:    astikit.BoolPtr(true),
			},
		},
	}))
}
